### ISSUE TITLE
Consider calculating `role` for each operator

### ISSUE THREAD

**Issue by stnokott** [redraskal/r6-dissect#28]
As continued from #27 :

> I think we just need a way to calculate what role each operator is part of, so we can assign the team `role` based on what the players pick.

@redraskal

**Comment by stnokott** [comment]
I think I understand now what you are suggesting. Is the following correct?

The current approach for deriving the team role:

1. Determine the spawn (seems unreliable)
2. If the spawn is empty, set the role to `ATTACK`, otherwise "DEFENSE"

Your suggested new approach:

1. Keep a map of `map[operatorName]role` or something similar (possibly automatically generated in some way)
2. Find out which operator a player picked
3. Find out which role this operator belongs to, thus finding out which role the player has
4. Assign the team's role based on the player's/the player's operator's role

**Comment by stnokott** [comment]
If the role is not actually present in the replay file or not easy to find or subject to change, then I think this is a good idea.

If you like, I can try implementing this.

**Comment by redraskal** [comment]
> If the role is not actually present in the replay file or not easy to find or subject to change, then I think this is a good idea.
> 
> 
> 
> If you like, I can try implementing this.

The name in the map could be the uint64 operator id. I think we are in sync with this.

You can implement this idea, I appreciate the help!

**Comment by stnokott** [comment]
Is it ok if I bump Go to 1.20 for this PR?
There are a few function I want to use that only became available in 1.20.

**Comment by redraskal** [comment]
Yes
