### ISSUE TITLE
Missing operator IDs in header.go

### ISSUE THREAD

**Issue by stnokott** [redraskal/r6-dissect#33]
Hey there,

while working on #31 , I discovered that `header.go` is missing a few operator IDs.
I guess that's also why I sometimes did not have an operator in my replay JSONs.

The operators in question are:

- Blitz
- Buck
- Clash
- Flores
- Frost
- Glaz
- Gridlock
- Grim
- Hibana
- IQ
- Jackal
- Maestro
- Maverick
- Oryx
- Sens
- Tachanka
- Thatcher
- Twitch

**Comment by redraskal** [comment]
Thanks for the list. I simply did not yet finish all of them. I’ll go through the rest today

**Comment by redraskal** [comment]
(This is why the operator did not always appear, it wasn't present)

You should instead see an operator id in the Player struct, which can then be set as a constant.
