### ISSUE TITLE
`ReadPartial` and `Read` yield conflicting operator data

### ISSUE THREAD

**Issue by stnokott** [redraskal/r6-dissect#40]
Using `r6-dissect` as a Go package and reading the **same** replay file once with `Read` and once with `ReadPartial` yields different operator IDs in some cases.

Minimum reproducible example can be found here: https://github.com/stnokott/r6-dissect-test

The above program prints the following output (for the same replay file):

> 2023/03/21 14:14:30 full players:
> 2023/03/21 14:14:30 0: Solis (391752120891)
> 2023/03/21 14:14:30 1: Capitao (92270644215)
> **2023/03/21 14:14:30 2: Amaru (104189663607)**
> 2023/03/21 14:14:30 3: Caveira (92270644241)
> 2023/03/21 14:14:30 4: Rook (92270644059)
> 2023/03/21 14:14:30 5: Glaz (92270642084)
> 2023/03/21 14:14:30 6: Lion (104189661861)
> 2023/03/21 14:14:30 7: Smoke (92270642396)
> 2023/03/21 14:14:30 8: Mozzie (174977508820)
> **2023/03/21 14:14:30 9: Blitz (92270642539)**
> 
> 2023/03/21 14:14:30 partial players:
> 2023/03/21 14:14:30 0: Solis (391752120891)
> 2023/03/21 14:14:30 1: Capitao (92270644215)
> **2023/03/21 14:14:30 2: Ash (92270642656)**
> 2023/03/21 14:14:30 3: Caveira (92270644241)
> 2023/03/21 14:14:30 4: Rook (92270644059)
> 2023/03/21 14:14:30 5: Glaz (92270642084)
> 2023/03/21 14:14:30 6: Lion (104189661861)
> 2023/03/21 14:14:30 7: Smoke (92270642396)
> 2023/03/21 14:14:30 8: Mozzie (174977508820)
> **2023/03/21 14:14:30 9: Twitch (92270644111)**

As mentioned above, indices 2 and 9 have different operator IDs for the two reads.

**Comment by redraskal** [comment]
ReadPartial stops before attack operator swaps are recorded. I'm guessing this is what happened. 

ReadPartial was designed for a fast cli output on the overview showing basic information like the map and game version.

**Comment by redraskal** [comment]
ReadPartial did not exist until the header stopped containing all players. So, I made a method to read up to this point. There is actually an entry in the file for all slots, even if untaken. So, I can safely read up until this point. I would not know when to stop if i also read operator swaps.

**Comment by stnokott** [comment]
Ah ok I see, that makes sense.
I had written a test that validates each player's operator. I guess I'll need to ignore that then for `ReadPartial`.

**Comment by redraskal** [comment]
Added a note in a recent PR. This will also be included on the online documentation when I get around to it
