### ISSUE TITLE
Recruit Operator not supported

### ISSUE THREAD

**Issue by redraskal** [redraskal/r6-dissect#45]
Dissect will panic on rounds with Recruit.

Recruit does not have a defined team role. How should we handle this?

**Operator ID:** 359656345734

**Comment by stnokott** [comment]
Huh, yeah didn't think about this edge-case.
This sounds like we'll need to move back to working with the spawns...

**Comment by redraskal** [comment]
> Huh, yeah didn't think about this edge-case. This sounds like we'll need to move back to working with the spawns...
Slipped my mind as well. There is likely some indicator for team role hidden in the replay files. Cannot say when this will be found.

I don't think we should panic in this case. Inferring the role on Recruit players from other players may be an alright solution for now

**Comment by redraskal** [comment]
I feel like the worst realistic case is an entire team of Recruit. Both teams Recruit are unlikely. We should be able to fairly reliably infer this and fill it in

**Comment by stnokott** [comment]
> Inferring the role on Recruit players from other players may be an alright solution for now

What if the whole team picks recruit though?

**Comment by stnokott** [comment]
> I feel like the worst realistic case is an entire team of Recruit. Both teams Recruit is unlikely. We should be able to fairly reliably infer this and fill it in

Honestly, I think having a whole team of recruits is more likely than just a single one when people are memeing.
How would you infer this? I feel the only reliable way of determining the role would be the spawn.

**Comment by redraskal** [comment]
> > I feel like the worst realistic case is an entire team of Recruit. Both teams Recruit is unlikely. We should be able to fairly reliably infer this and fill it in
> 
> Honestly, I think having a whole team of recruits is more likely than just a single one when people are memeing. How would you infer this? I feel the only reliable way of determining the role would be the spawn.

You are saying assign an attacker team role if a spawn is present and vise-versa? The problem is an attacking spawn is sometimes given to a defense player. I am clearing those invalid entries out by later checking the team role. So, I'm not sure this would work.

You could find the role of the other team that is not full Recruit and then assign the opposite roles to defense. I rarely see both teams go full recruit.

**Comment by redraskal** [comment]
Eventually, there should be a way to figure this out through the replay files

**Comment by redraskal** [comment]
For now, I will ignore Recruit in deriveTeamRoles. The function will work as long as one player does not pick Recruit. I think this is a good enough solution for this project.

Operator team roles are sometimes modified in events, but Ubisoft disables replay access so we cannot even use r6-dissect in these cases. So, a defense op will always be on defense and an attack op will always be on attack in any given replay file.
