### ISSUE TITLE
Nether team wins a round.

### ISSUE THREAD

**Issue by James-Sergeant** [redraskal/r6-dissect#47]
In this case as shown below both teams won flag is set to false, with no win condition. Where in the case of this round team 0 won by KilledOpponents is the expected output.
`   "teams": [
        {
            "name": "BLUE TEAM",
            "score": 3,
            "won": false,
            "role": "Attack"
        },
        {
            "name": "ORANGE TEAM",
            "score": 3,
            "won": false,
            "role": "Defense"
        }`

**To Reproduce**
Steps to reproduce the behaviour:
1. Get the rec files for EUL2023 stage 1 play day 6 Chalet VP vs secret round 6.
2. The JSON output for this round shows the above.

**Expected behaviour**
According to seige GG this round should be a win for secret by elimination: 
https://siege.gg/matches/9109-eul-eu-team-secret-vs-virtuspro

**Comment by redraskal** [comment]
It looks like VP won on attack by elimination. VP planted defuser after 4 kills. Final kill occurred post plant.

Are are talking about the same file? I'm using "Match-2023-03-28_18-02-30-75-R06.rec"

The roundEnd function that calculates the winning team was never called. Currently, r6-dissect relies on the end of round replay to run the winning team logic. This should be moved to the end of the read. I can fix this today.

```bash
2:23PM DBG match_update={"message":"Friendly Fire is now active","time":"2:59","timeInSeconds":179,"type":{"id":10,"name":"Other"}}
2:23PM DBG match_update={"headshot":true,"target":"Slebben.SECRET","time":"1:49","timeInSeconds":109,"type":{"id":0,"name":"Kill"},"username":"JoyStiCK.VP"}
2:23PM DBG match_update={"headshot":true,"target":"p4sh4.VP","time":"1:47","timeInSeconds":107,"type":{"id":0,"name":"Kill"},"username":"yzn.SECRET"}
2:23PM DBG match_update={"headshot":true,"target":"Savage.SECRET","time":"1:24","timeInSeconds":84,"type":{"id":0,"name":"Kill"},"username":"dan-_-.VP"}
2:23PM DBG match_update={"headshot":false,"target":"dan-_-.VP","time":"1:19","timeInSeconds":79,"type":{"id":0,"name":"Kill"},"username":"Astro.SECRET"}
2:23PM DBG match_update={"headshot":true,"target":"Gruby.SECRET","time":"1:13","timeInSeconds":73,"type":{"id":0,"name":"Kill"},"username":"JoyStiCK.VP"}
2:23PM DBG match_update={"headshot":false,"target":"JoyStiCK.VP","time":"0:44","timeInSeconds":44,"type":{"id":0,"name":"Kill"},"username":"Astro.SECRET"}
2:23PM DBG match_update={"headshot":false,"target":"Astro.SECRET","time":"0:12","timeInSeconds":12,"type":{"id":0,"name":"Kill"},"username":"Always.VP"}
2:23PM DBG match_update={"time":"0:10","timeInSeconds":10,"type":{"id":2,"name":"DefuserPlantStart"},"username":"ShepparD.VP"}
2:23PM DBG match_update={"time":"0:03","timeInSeconds":3,"type":{"id":3,"name":"DefuserPlantComplete"},"username":"ShepparD.VP"}
2:23PM DBG match_update={"headshot":false,"target":"yzn.SECRET","time":"0:00","timeInSeconds":0,"type":{"id":0,"name":"Kill"},"username":"ShepparD.VP"}
```

**Comment by redraskal** [comment]
I have not had time to test recently, but potential fixes are on the `dev` branch!

**Comment by redraskal** [comment]
do you still see occurrences of this bug @James-Sergeant

**Comment by redraskal** [comment]
one of the tests had this issue- the problem is fixed. let me know if you encounter this again
