### ISSUE TITLE
Live Match Information

### ISSUE THREAD

**Issue by SwiftCODA** [redraskal/r6-dissect#49]
Hello, @redraskal, @stnokott, and any other developers reading this.
A group of developers, along with myself are working to find the source for live match information on all platforms––some way to pass a profileId into the request, and get back a list of all opponents of that player in the match they are currently in.

There is currently a $1000 bounty for whoever solves this. All are welcome to participate in the research and investigation.

Please check out https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/issues/11

**Comment by redraskal** [comment]
Personally, I don't think this would exist. There is no reason for them to provide public live match information- especially due to the streamer mode system. A publicly accessible endpoint would defeat the point of nicknames

**Comment by stnokott** [comment]
TabStats looks pretty dead to me, overlay and page aren't working.

**Comment by SwiftCODA** [comment]
> TabStats looks pretty dead to me, overlay and page aren't working.
> 
> Was thinking about sniffing their overlay, but it's non-functional on my end. Is that the only known software that exposes the data you're looking for?

On their website if you make an account, you can use their feature called TabLive, which lets you put in your username for R6 and see all the players in your match.

**Comment by redraskal** [comment]
> > TabStats looks pretty dead to me, overlay and page aren't working.
> > Was thinking about sniffing their overlay, but it's non-functional on my end. Is that the only known software that exposes the data you're looking for?
> 
> On their website if you make an account, you can use their feature called TabLive, which lets you put in your username for R6 and see all the players in your match.

Interesting. I will comment on that issue if I stumble upon this method
