### ISSUE TITLE
New Operator

### ISSUE THREAD

**Issue by SablyTv** [redraskal/r6-dissect#51]
**Describe the bug**
Needs to be updated to include the new operator Fenrir. Crashes: "role unknown for operator ID 288200867339"
I tried adding it myself in operator_roles.go and operator_string.go but now getting "role unknown for operator ID 0"

**To Reproduce**
1. Play a match and make sure the new operator Fenrir is in match.
2. Try to run the dessector on the match replay files
3. Crashes...

**Comment by redraskal** [comment]
Should be fixed in latest release!
