### ISSUE TITLE
New Season Compatibility (r6-dissect-0.11.0)

### ISSUE THREAD

**Issue by OAbbass** [redraskal/r6-dissect#52]
**Describe the bug**
Executing the r6-dissect on replay files from Y8S2 with a json output will cause an error stopping the program from working

**To Reproduce**
1. Open a cmd line in r6-dissect directory
2. Type in the cmd line enter "r6-dissect | path of your replay file | -x | output file name.json |" (without quotations)

**Expected behavior**
A json file with the specified output name containing all the match details.

**Additional context**
![InkedCapture](https://github.com/redraskal/r6-dissect/assets/64077081/156e0eff-cba8-47fd-b414-9904d70c6a6b)

No additional context.

**Comment by hoxnets** [comment]
I can confirm this happens for any type of operation.
![image](https://github.com/redraskal/r6-dissect/assets/136173621/34e7d001-7610-443c-9bca-e1415eae6738)

**Comment by KevinCCucumber** [comment]
I can add to this:

```
panic: role unknown for operator ID 0

goroutine 1 [running]:
github.com/redraskal/r6-dissect/dissect.Operator.Role(...)
        /github/workspace/dissect/operator_roles.go:81
github.com/redraskal/r6-dissect/dissect.(*Reader).deriveTeamRoles(0xc0002bc200)
        /github/workspace/dissect/header.go:501 +0x459
github.com/redraskal/r6-dissect/dissect.(*Reader).readPlayer.func1()
        /github/workspace/dissect/player.go:21 +0x25
github.com/redraskal/r6-dissect/dissect.(*Reader).readPlayer(0xc0002bc200)
        /github/workspace/dissect/player.go:150 +0x1031
github.com/redraskal/r6-dissect/dissect.(*Reader).Read(0xc0002bc200)
        /github/workspace/dissect/reader.go:82 +0x19e
main.exportRound({0xc00007e180?, 0x12c512b?}, {0xc00000c0f0, 0xa})
        /github/workspace/main.go:153 +0xf0
main.main()
        /github/workspace/main.go:52 +0x2f2
```

**Comment by redraskal** [comment]
thank you for the comments, i'm working on fixing the remaining issuues

**Comment by redraskal** [comment]
publishing a new release- should hopefully fix these issues

**Comment by OAbbass** [comment]
Can confirm the latest patch solved the issue.

**Comment by OAbbass** [comment]
I saw. Thanks again man. You've been huge man.
