### ISSUE TITLE
1F Open Area name shows up in json as Lockers/CCTV

### ISSUE THREAD

**Issue by Zander-9909** [redraskal/r6-dissect#54]
**Describe the bug**
1st floor Open Area site name on Bank is detected as Lockers/CCTV (only played once, so I don't know if it is a one off)
It seems like just the name is but I am not sure. All other sites are fine
**To Reproduce**
Play a round on Open area

**Expected behavior**
Open area would be detected as 1F Staff Room, 1F Open Area

**Additional context**
This was in a custom game if that makes any difference

**Comment by redraskal** [comment]
Can you send the log with the debug flag (-d)? I will see if I can replicate it

**Comment by redraskal** [comment]
i think sites have since been fixed. if you find another case, please send a replay file
