### ISSUE TITLE
Inaccurate Repeating Site Names

### ISSUE THREAD

**Issue by Sleepy-Git-User** [redraskal/r6-dissect#55]
**Describe the bug**
After running a few rec files from LATAM and Brazil BLAST on the new version of R6 Dissect I noticed Defender site names arent being reportedly properly and are repeating the same site name over and over again after getting a few correct.

**To Reproduce**
1. Run R6 Dissect on a LATAM Blast match.
2. Check a few of the sites being played in the JSON and youll see repeating sites.
3. After checking the vod you can see the sites being reported are wrong.

**Expected behavior**
The JSONs should reflect the correct site being picked.

**Additional context**
Here is a vod link to one of the effect matches: https://www.youtube.com/live/sJ96LEBygNk?feature=share&t=2907,https://www.youtube.com/live/sJ96LEBygNk?feature=share&t=6783

**Comment by redraskal** [comment]
i’ll look at the vod, likely the same issue as #54 and related to #56

**Comment by redraskal** [comment]
should be fixed in latest version! please send a replay file or link to a replay package from r6 esports if this is still not the case
