### ISSUE TITLE
panic: role unknown for operator ID 0

### ISSUE THREAD

**Issue by hanslhansl** [redraskal/r6-dissect#66]
The attached replay file causes the r6-dissect.exe file to output this error message:
"panic: role unknown for operator ID 0

goroutine 1 [running]:
github.com/redraskal/r6-dissect/dissect.Operator.Role(...)
        /github/workspace/dissect/operator_roles.go:82
github.com/redraskal/r6-dissect/dissect.(*Reader).deriveTeamRoles(0xc0002c66c0)
        /github/workspace/dissect/header.go:508 +0x5db
github.com/redraskal/r6-dissect/dissect.(*Reader).readPlayer.func1()
        /github/workspace/dissect/player.go:21 +0x27
github.com/redraskal/r6-dissect/dissect.(*Reader).readPlayer(0xc0002c66c0)
        /github/workspace/dissect/player.go:158 +0x1271
github.com/redraskal/r6-dissect/dissect.(*Reader).Read(0xc0002c66c0)
        /github/workspace/dissect/reader.go:138 +0x5cf
main.exportRound({0xc00006e100?, 0xf8822a?}, {0xc00000e0e8, 0x6})
        /github/workspace/main.go:155 +0xf0
main.main()
        /github/workspace/main.go:52 +0x2f2"

The command line is:
"[...]\Tom Clancy's Rainbow Six Siege\MatchReplay\Match-2023-09-21_21-34-28-63\Match-2023-09-21_21-34-28-63-R02.rec" -x stdout

I attached the replay file in question to this post but renamed it to end with .png as Github only allows specific file endings.

![Match-2023-09-21_21-34-28-63-R02](https://github.com/redraskal/r6-dissect/assets/46355861/9beebde8-e91b-44ac-9309-4b3678059609)

**Comment by redraskal** [comment]
do you experience the error in any other matches @hanslhansl? looks like "elothief27" had no operator data.

this normally occurs when a player slot is empty

**Comment by redraskal** [comment]
i saw a message "elothief277 has returned" in the replay file. did the player lose connection in round 1 and rejoin?

i'm guessing the player did not compete in round 2, so siege sent fragmented data

**Comment by hanslhansl** [comment]
> i saw a message "elothief277 has returned" in the replay file. did the player lose connection in round 1 and rejoin?
> 
> i'm guessing the player did not compete in round 2, so siege sent fragmented data

I just rewatched the round and that is exactly what happened.

Is r6-dissect intended to throw an error in such a situation?

**Comment by redraskal** [comment]
no, i might go with printing a warning and omitting the operator if this happens

**Comment by redraskal** [comment]
should be fixed in next release
