### ISSUE TITLE
Attacker round victory by defusing counts as victory for the defenders

### ISSUE THREAD

**Issue by hanslhansl** [redraskal/r6-dissect#68]
![Match-2023-10-07_22-43-33-242-R06](https://github.com/redraskal/r6-dissect/assets/46355861/30be163a-40b6-4bf1-b994-81a3137c1102)

The round I attached (file renamed to .png because of Github limitations) is the 6th round in a match. Defenders are leading 3:2. The attackers win this round by planting the defuser. The round ends after the 40 seconds defuser time-out (not by the attackers killing the defenders). Yet r6-dissect counts the round as a win for the defenders (by win condition 'Time').

Additionally, r6-dissect prints these two warnings:
- 'WRN tracked players greater than 10'
- 'WRN operator id was 0, removing from list username=Bucky-_-'

However, it prints these warnings for all 8 rounds of the match, not only for round 6 mentioned earlier, so I am not sure if those warnings are even related to original problem.

**Comment by redraskal** [comment]
likely just an error with calculating the win condition. those two warnings are only bad if you see incorrect player information in the "players" object

**Comment by redraskal** [comment]
the plant in this replay was not properly recorded, so dissect defaults to a defense win by Time

**Comment by redraskal** [comment]
winning team fixed in Y9S4 release, although the win condition may still be incorrect at times because of the defuser feature being broken
