### ISSUE TITLE
Replays of the new season Deep Freeze all cause the same error

### ISSUE THREAD

**Issue by hanslhansl** [redraskal/r6-dissect#70]
I've tried multiple match replay folders as well as match replay files and all of them cause 'FTL error="dissect: received an invalid length of bytes"'.

The match replays I am talking about were generated by the game with the new Deep Freeze patch installed.
I am using the r6-dissect.exe from the most recent Windows release.

**Comment by redraskal** [comment]
maybe something happened since the test server, i will check soon

**Comment by redraskal** [comment]
@hanslhansl hey, i cannot replicate this issue. could you send a replay file and tell me what mode the replay is from (quick play, vs ai, etc)

**Comment by f870103** [comment]
@redraskal here is a standard match replay file with the same error.

```shell
Analyzing Match-2023-12-07_20-35-16-59...
1:30PM INF Reading round 1/7...
1:30PM FTL error="dissect: received an invalid length of bytes"
```

[Match-2023-12-07_20-35-16-59-R01.zip](https://github.com/redraskal/r6-dissect/files/13622787/Match-2023-12-07_20-35-16-59-R01.zip)

**Comment by redraskal** [comment]
still broken in some cases lol, will fix soon

**Comment by Annabxlla** [comment]
Issue has been fixed this bug report can be closed.
