### ISSUE TITLE
Player ID's are all the same

### ISSUE THREAD

**Issue by DansArchive** [redraskal/r6-dissect#74]
**Describe the bug**
Within the players object all the ids associated for each individual player appear to be the same. Additionally some replays have the same ID as the previous, however others don't

**Comment by redraskal** [comment]
profileID is more relevant now. You can even use this ID with the Ubisoft stats API. I'm not sure what id refers to. The value is inconsistent

**Comment by redraskal** [comment]
somewhat fixed, one team will now have "id"

**Comment by redraskal** [comment]
the "id" looks unused, may remove in a future release
