### ISSUE TITLE
Issues with bun

### ISSUE THREAD

**Issue by Annabxlla** [redraskal/r6-dissect#77]
**Describe the bug**
When using `dissectMatch` from "r6-dissect" (from npm) you get the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x7ff117dd1a97]

goroutine 17 [running, locked to thread]:
github.com/redraskal/r6-dissect/dissect.(*Reader).PlayerStats(0x0)
        /github/workspace/dissect/stats.go:82 +0xb7
github.com/redraskal/r6-dissect/dissect.(*MatchReader).Data(0xc0001df280)
        /github/workspace/dissect/match.go:236 +0xbc
main.dissect_read(0x0?)
        /github/workspace/exports/exports.go:57 +0xd4
Aborted
```

When using `dissect` from "r6-dissect" you get the following error:
`invalid input: magic number mismatch`

**To Reproduce**
1. Import the latest "r6-dissect" from NPM, using `bun i r6-dissect`
2. Import the dissect/dissectMatch from "r6-dissect" (as one would normally with bun)
3. Try to read the data of a Match directory / round .rec file; example `const { data, error } = await dissectMatch("Match-2023-12-27_20-41-51-74/");`
4. Observe the error in console.
 

**Expected behavior**
I feel like the expected behavior is quite apparent but, I would expect it to `console.log(data.matchID)`

**Additional context**
This is running on Ubuntu 22.04 LTS via WSL
This is using the Latest Release of r6-dissect via NPM
This is also a fresh install of Ubuntu.

**Comment by redraskal** [comment]
@Annabxlla try the latest npm release, should be fixed. i think this was due to an outdated binary included in that release. i might change the workflow for the bun package to download (and cache) on runtime as opposed to including the binaries in releases
