### ISSUE TITLE
Opponents team player is not in the player list.

### ISSUE THREAD

**Issue by developer-ken** [redraskal/r6-dissect#8]
**Is your feature request related to a problem? Please describe.**
I am working on a project that depend on reading R6 replays. I tried this repo and find it amazing.  
I noticed players in the opponents team is not in that player list in the output json file.  
Will it be possible to have that?

**Describe alternatives you've considered**
For now, I can just use information in activity feed, record any player mentioned not in the player list to obtain extra info.

**Comment by redraskal** [comment]
> **Is your feature request related to a problem? Please describe.** I am working on a project that depend on reading R6 replays. I tried this repo and find it amazing. I noticed players in the opponents team is not in that player list in the output json file. Will it be possible to have that?
> 
> **Describe alternatives you've considered** For now, I can just use information in activity feed, record any player mentioned not in the player list to obtain extra info.

Will look into this. Ubisoft updated the game a few months ago and removed one team from the header for some reason :) This data will be available elsewhere in replay files, but I have not yet spent enough time analyzing it.

**Comment by redraskal** [comment]
Added the missing team's username, Ubisoft stats ID, and team index. The operator and other data will be missing for the time being
