### ISSUE TITLE
"won" attribute set inconsistently with "score" attribute for defuser planted in last second edge case

### ISSUE THREAD

**Issue by CodingPenguin1** [redraskal/r6-dissect#86]
**Describe the bug**
Team can be marked as having won a round even though the lost it. Score is updated correctly.

**To Reproduce**
I believe this issue is caused when the defuser is finished being planted after the action phase ends. In the case I found, there was a 1v1 in the last seconds of the round. The attacker planted the defuser, starting before the round ended, and finishing after the round would have ended. This, of course, adds 45s to the timer for the defender to stop the defuser. In this case, that happened. The defender killed the attacker and stopped the defuser. The following was output to the JSON after running r6-dissect

```json
"teams": [
    {
        "name": "Kenough Uni",
        "score": 6,
        "won": false,
        "role": "Defense"
    },
    {
        "name": "UC Acad",
        "score": 0,
        "won": true,
        "winCondition": "DefusedBomb",
        "role": "Attack"
    }
```

**Expected behavior**
The "won" value should be flipped for each team. "Kenough Uni" should have `true` for "won" and "UC Acad" `false`.

**Comment by redraskal** [comment]
will look at this soon, might be an issue with this method

https://github.com/redraskal/r6-dissect/blob/00593f18355bb78328d01293092faad59e1195f7/dissect/time.go#L45

**Comment by redraskal** [comment]
the defuser disable event was likely not recorded, so the win condition defaults to a defuse.

**Comment by redraskal** [comment]
can you send the replay to ben@ctos.sh @CodingPenguin1?

my guess is the match timer was not at 0.00, so the disable event was ignored

**Comment by CodingPenguin1** [comment]
@redraskal sent

**Comment by redraskal** [comment]
@CodingPenguin1 the disable timer did not reach 0 when stopped. r6-dissect should probably rely on an actual defuser state as opposed to the timer.

this requires more research, not sure when i'll have a solution

**Comment by CodingPenguin1** [comment]
No worries, glad to have found an edge case for you

**Comment by redraskal** [comment]
winning team fixed in Y9S4 release, although the win condition may still be incorrect at times because of the defuser feature being broken
