### ISSUE TITLE
1vX stat broken when plant is down

### ISSUE THREAD

**Issue by Bunnykiller914** [redraskal/r6-dissect#88]
The 1vX stat does not appear for a player that won a 1vX then defused. The score for the teams increased properly, but the win boolean is set to false for their team. I believe this is what makes the 1vx not appear. The 1vx does appear for a player on the team that planted - although this person lost the 1v1.

**Snippets of json**
{
                    "name": "YOUR TEAM",
                    "score": 4,
                    "won": true,
                    "winCondition": "DefusedBomb",
                    "role": "Attack"
                },
                {
                    "name": "OPPONENTS",
                    "score": 1,
                    "won": false,
                    "role": "Defense"
}

"Opponents" won here, but won is set to false.

{
                    "type": {
                        "name": "DefuserPlantStart",
                        "id": 2
                    },
                    "username": "UNiTY_Imp3r1um",
                    "time": "0:54",
                    "timeInSeconds": 54
                },
                {
                    "type": {
                        "name": "DefuserPlantComplete",
                        "id": 3
                    },
                    "username": "UNiTY_Imp3r1um",
                    "time": "0:47",
                    "timeInSeconds": 47
                },
                {
                    "type": {
                        "name": "Kill",
                        "id": 0
                    },
                    "username": "DugBolt_MCC",
                    "target": "Yeti_.AWP",
                    "headshot": true,
                    "time": "0:29",
                    "timeInSeconds": 29
                },
                {
                    "type": {
                        "name": "Kill",
                        "id": 0
                    },
                    "username": "DugBolt_MCC",
                    "target": "UNiTY_Imp3r1um",
                    "headshot": true,
                    "time": "0:16",
                    "timeInSeconds": 16
                },
                {
                    "type": {
                        "name": "DefuserDisableStart",
                        "id": 4
                    },
                    "username": "DugBolt_MCC",
                    "time": "0:11",
                    "timeInSeconds": 11
                }
}

Unity planted and was left in a 2 (atk) v 1 (def). DugBolt killed Unity and Yeti, then defused.

{
                    "username": "DugBolt_MCC",
                    "score": 1528,
                    "kills": 5,
                    "died": false,
                    "assists": 0,
                    "headshots": 3,
                    "headshotPercentage": 60
                },
         {
                    "username": "UNiTY_Imp3r1um",
                    "score": 0,
                    "kills": 0,
                    "died": true,
                    "assists": 0,
                    "headshots": 0,
                    "headshotPercentage": 0,
                    "1vX": 1
                },

DugBolt does not have a 1vx, and Unity does.

**Json from the round, .rec is in discord server**
[Round5.json](https://github.com/redraskal/r6-dissect/files/14588497/Round5.json)

**Comment by redraskal** [comment]
i think this is the same as #86, not sure when i will have a solution. basically, the defuse could not be tracked. check that issue for any updates
