### ISSUE TITLE
Incorrect `matchFeedback` message in JSON output

### ISSUE THREAD

**Issue by f870103** [redraskal/r6-dissect#89]
I'm encountering an issue with the `matchFeedback` field in the JSON output file generated by version `v0.19.0` when using a Y9S1 replay file.
The `message` property within `matchFeedback` objects contains unreadable characters like `\ufffd\ufffd\ufffd\ufffd` and `\ufffd\ufffd\u0005\u0000`.

```json
"matchFeedback": [{
                    "type": {
                        "name": "Other",
                        "id": 10
                    },
                    "time": "0:00",
                    "timeInSeconds": 0,
                    "message": "\ufffd\ufffd\ufffd\ufffd"
                }, {
                    "type": {
                        "name": "Other",
                        "id": 10
                    },
                    "time": "0:00",
                    "timeInSeconds": 0,
                    "message": "\ufffd\ufffd\u0005\u0000"
                }, {
                    "type": {
                        "name": "Other",
                        "id": 10
                    },
                    "time": "2:59",
                    "timeInSeconds": 179,
                    "message": "\ufffd\ufffd\u0005\u0000"
                },
```

This issue has been observed on all my standard matches so far. I'm not sure if other match types are affected.

[Match-2024-03-13_22-26-58-200-R01.zip](https://github.com/redraskal/r6-dissect/files/14670247/Match-2024-03-13_22-26-58-200-R01.zip)
[Match-2024-03-13_22-26-58-200.json](https://github.com/redraskal/r6-dissect/files/14670251/Match-2024-03-13_22-26-58-200.json)

**Comment by redraskal** [comment]
I think match feedback changed in Y9S1. For instance, I no longer see messages for locating the objective. This may have been migrated over to a more efficient binary format.

Right now, I am fixing the kill feed and will likely suppress other messages for now.

**Comment by redraskal** [comment]
The problem should be resolved in https://github.com/redraskal/r6-dissect/releases/tag/v0.19.1. Let me know if this is not the case!
