### ISSUE TITLE
Downs finished by another player are counted towards the wrong player's kill count

### ISSUE THREAD

**Issue by CodingPenguin1** [redraskal/r6-dissect#92]
It appears that a kill is counted for a particular player if that player shows up in the kill feed. This is not always correct though, as a player who downs an enemy should be granted the kill, even if a teammate finishes the downed player. I have a match replay demonstrating this.

**Comment by redraskal** [comment]
Yes, this project uses the kill feed to count kills and accidental deaths. I do not know of a way to check for downs

**Comment by redraskal** [comment]
I will keep this in mind if I come across something

**Comment by redraskal** [comment]
May have a solution soon

**Comment by redraskal** [comment]
if you're still interested in this, would you mind testing @CodingPenguin1?

**Comment by CodingPenguin1** [comment]
> if you're still interested in this, would you mind testing @CodingPenguin1?
> 
> [r6-dissect.zip](https://github.com/user-attachments/files/16652851/r6-dissect.zip)

I would if I remembered which replay I noticed the issue on. My bad for not documenting. Been a while since I've looked at this, or even opened siege for that matter
